// The following defines have been taken from https://github.com/bnoordhuis/strace/blob/master/defs.h#L541
#define TRACE_FILE  001 /* Trace file-related syscalls. */
#define TRACE_IPC 002 /* Trace IPC-related syscalls. */
#define TRACE_NETWORK 004 /* Trace network-related syscalls. */
#define TRACE_PROCESS 010 /* Trace process-related syscalls. */
#define TRACE_SIGNAL  020 /* Trace signal-related syscalls. */
#define TRACE_DESC  040 /* Trace file descriptor-related syscalls. */
#define TRACE_MEMORY  0100  /* Trace memory mapping-related syscalls. */
#define SYSCALL_NEVER_FAILS 0200  /* Syscall is always successful. */
#define STACKTRACE_INVALIDATE_CACHE 0400  /* Trigger proc/maps cache updating */
#define STACKTRACE_CAPTURE_ON_ENTER 01000 /* Capture stacktrace on "entering" stage */
#define TRACE_INDIRECT_SUBCALL  02000 /* Syscall is an indirect socket/ipc subcall. */

// The following defines have been taken from https://github.com/bnoordhuis/strace/blob/master/syscall.c#L94
#define TD TRACE_DESC
#define TF TRACE_FILE
#define TI TRACE_IPC
#define TN TRACE_NETWORK
#define TP TRACE_PROCESS
#define TS TRACE_SIGNAL
#define TM TRACE_MEMORY
#define NF SYSCALL_NEVER_FAILS
#define MA MAX_ARGS
#define SI STACKTRACE_INVALIDATE_CACHE
#define SE STACKTRACE_CAPTURE_ON_ENTER

#define sys_accept 0
#define sys_accept4 0
#define sys_access 0
#define sys_add_key 0
#define sys_adjtimex 0
#define sys_arch_prctl 0
#define sys_bind 0
#define sys_brk 0
#define sys_capget 0
#define sys_capset 0
#define sys_chdir 0
#define sys_chmod 0
#define sys_chown 0
#define sys_clock_adjtime 0
#define sys_clock_gettime 0
#define sys_clock_nanosleep 0
#define sys_clock_settime 0
#define sys_clone 0
#define sys_close 0
#define sys_connect 0
#define sys_creat 0
#define sys_create_module 0
#define sys_delete_module 0
#define sys_dup 0
#define sys_dup2 0
#define sys_dup3 0
#define sys_epoll_create 0
#define sys_epoll_create1 0
#define sys_epoll_ctl 0
#define sys_epoll_pwait 0
#define sys_epoll_wait 0
#define sys_eventfd 0
#define sys_eventfd2 0
#define sys_execve 0
#define sys_exit 0
#define sys_faccessat 0
#define sys_fadvise64 0
#define sys_fadvise64_64 0
#define sys_fallocate 0
#define sys_fanotify_init 0
#define sys_fanotify_mark 0
#define sys_fchmod 0
#define sys_fchmodat 0
#define sys_fchown 0
#define sys_fchownat 0
#define sys_fcntl 0
#define sys_fgetxattr 0
#define sys_finit_module 0
#define sys_flistxattr 0
#define sys_flock 0
#define sys_fork 0
#define sys_fremovexattr 0
#define sys_fsetxattr 0
#define sys_fstat 0
#define sys_fstat64 0
#define sys_fstatfs 0
#define sys_fstatfs64 0
#define sys_ftruncate 0
#define sys_ftruncate64 0
#define sys_futex 0
#define sys_futimesat 0
#define sys_get_mempolicy 0
#define sys_get_robust_list 0
#define sys_get_thread_area 0
#define sys_getcpu 0
#define sys_getcwd 0
#define sys_getdents 0
#define sys_getdents64 0
#define sys_getdtablesize 0
#define sys_getgroups 0
#define sys_gethostname 0
#define sys_getitimer 0
#define sys_getpmsg 0 /* TODO: non-Linux, remove? */
#define sys_getpriority 0
#define sys_getresuid 0
#define sys_getrlimit 0
#define sys_getrusage 0
#define sys_getsockname 0
#define sys_getsockopt 0
#define sys_gettimeofday 0
#define sys_getuid 0
#define sys_getxattr 0
#define sys_init_module 0
#define sys_inotify_add_watch 0
#define sys_inotify_init1 0
#define sys_inotify_rm_watch 0
#define sys_io_cancel 0
#define sys_io_destroy 0
#define sys_io_getevents 0
#define sys_io_setup 0
#define sys_io_submit 0
#define sys_ioctl 0
#define sys_ioprio_get 0
#define sys_ioprio_set 0
#define sys_ipc 0
#define sys_keyctl 0
#define sys_kexec_load 0
#define sys_kill 0
#define sys_link 0
#define sys_linkat 0
#define sys_listen 0
#define sys_listxattr 0
#define sys_llseek 0
#define sys_lseek 0
#define sys_madvise 0
#define sys_mbind 0
#define sys_migrate_pages 0
#define sys_mincore 0
#define sys_mknod 0
#define sys_mknodat 0
#define sys_mlockall 0
#define sys_mmap 0
#define sys_mmap_pgoff 0
#define sys_mmap_4koff 0
#define sys_modify_ldt 0
#define sys_mount 0
#define sys_move_pages 0
#define sys_mprotect 0
#define sys_mq_getsetattr 0
#define sys_mq_notify 0
#define sys_mq_open 0
#define sys_mq_timedreceive 0
#define sys_mq_timedsend 0
#define sys_mremap 0
#define sys_msgctl 0
#define sys_msgget 0
#define sys_msgrcv 0
#define sys_msgsnd 0
#define sys_msync 0
#define sys_munmap 0
#define sys_nanosleep 0
#define sys_newfstatat 0
#define sys_old_mmap 0
#define sys_old_mmap_pgoff 0
#define sys_oldfstat 0
#define sys_oldselect 0
#define sys_oldstat 0
#define sys_open 0
#define sys_openat 0
#define sys_perf_event_open 0
#define sys_personality 0
#define sys_pipe 0
#define sys_pipe2 0
#define sys_poll 0
#define sys_poll 0
#define sys_ppoll 0
#define sys_prctl 0
#define sys_pread 0
#define sys_preadv 0
#define sys_prlimit64 0
#define sys_process_vm_readv 0
#define sys_process_vm_writev 0
#define sys_pselect6 0
#define sys_ptrace 0
#define sys_putpmsg 0
#define sys_pwrite 0
#define sys_pwritev 0
#define sys_query_module 0
#define sys_quotactl 0
#define sys_read 1
#define sys_readahead 0
#define sys_readdir 0
#define sys_readlink 0
#define sys_readlinkat 0
#define sys_readv 0
#define sys_reboot 0
#define sys_recv 0
#define sys_recvfrom 0
#define sys_recvmmsg 0
#define sys_recvmsg 0
#define sys_remap_file_pages 0
#define sys_removexattr 0
#define sys_renameat 0
#define sys_renameat2 0
#define sys_request_key 0
#define sys_restart_syscall 0
#define sys_rt_sigaction 0
#define sys_rt_sigpending 0
#define sys_rt_sigprocmask 0
#define sys_rt_sigqueueinfo 0
#define sys_rt_sigsuspend 0
#define sys_rt_sigtimedwait 0
#define sys_rt_tgsigqueueinfo 0
#define sys_sched_get_priority_min 0
#define sys_sched_getaffinity 0
#define sys_sched_getparam 0
#define sys_sched_getscheduler 0
#define sys_sched_rr_get_interval 0
#define sys_sched_setaffinity 0
#define sys_sched_setparam 0
#define sys_sched_setscheduler 0
#define sys_select 0
#define sys_semctl 0
#define sys_semget 0
#define sys_semop 0
#define sys_semtimedop 0
#define sys_send 0
#define sys_sendfile 0
#define sys_sendfile64 0
#define sys_sendmmsg 0
#define sys_sendmsg 0
#define sys_sendto 0
#define sys_set_mempolicy 0
#define sys_set_thread_area 0
#define sys_setfsuid 0
#define sys_setgroups 0
#define sys_sethostname 0
#define sys_setitimer 0
#define sys_setns 0
#define sys_setpriority 0
#define sys_setresuid 0
#define sys_setreuid 0
#define sys_setrlimit 0
#define sys_setsockopt 0
#define sys_settimeofday 0
#define sys_setuid 0
#define sys_setxattr 0
#define sys_shmat 0
#define sys_shmctl 0
#define sys_shmdt 0
#define sys_shmget 0
#define sys_shutdown 0
#define sys_sigaction 0
#define sys_sigaltstack 0
#define sys_siggetmask 0
#define sys_signal 0
#define sys_signalfd 0
#define sys_signalfd4 0
#define sys_sigpending 0
#define sys_sigprocmask 0
#define sys_sigreturn 0
#define sys_sigsetmask 0
#define sys_sigsuspend 0
#define sys_socket 0
#define sys_socketcall 0
#define sys_socketpair 0
#define sys_splice 0
#define sys_stat 0
#define sys_stat64 0
#define sys_statfs 0
#define sys_statfs64 0
#define sys_swapon 0
#define sys_symlinkat 0
#define sys_sync_file_range 0
#define sys_sync_file_range2 0
#define sys_sysctl 0
#define sys_sysinfo 0
#define sys_syslog 0
#define sys_tee 0
#define sys_tgkill 0
#define sys_time 0
#define sys_timer_create 0
#define sys_timer_gettime 0
#define sys_timer_settime 0
#define sys_timerfd 0
#define sys_timerfd_create 0
#define sys_timerfd_gettime 0
#define sys_timerfd_settime 0
#define sys_times 0
#define sys_truncate 0
#define sys_truncate64 0
#define sys_umask 0
#define sys_umount2 0
#define sys_uname 0
#define sys_unlinkat 0
#define sys_unshare 0
#define sys_utime 0
#define sys_utimensat 0
#define sys_utimes 0
#define sys_vmsplice 0
#define sys_wait4 0
#define sys_waitid 0
#define sys_waitpid 0
#define sys_write 1
#define sys_writev 0
#define sys_lstat 0
#define sys_rt_sigreturn 0
#define sys_sched_yield 0
#define sys_pause 0
#define sys_alarm 0
#define sys_getpid 0
#define sys_getpeername 0
#define sys_vfork 0
#define sys_fsync 0
#define sys_fdatasync 0
#define sys_fchdir 0
#define sys_rename 0
#define sys_mkdir 0
#define sys_rmdir 0
#define sys_unlink 0
#define sys_symlink 0
#define sys_getgid 0
#define sys_setgid 0
#define sys_geteuid 0
#define sys_getegid 0
#define sys_setpgid 0
#define sys_getppid 0
#define sys_getpgrp 0
#define sys_setsid 0
#define sys_setregid 0
#define sys_setresgid 0
#define sys_getresgid 0
#define sys_getpgid 0
#define sys_setfsgid 0
#define sys_getsid 0
#define sys_uselib 0
#define sys_ustat 0
#define sys_sysfs 0
#define sys_sched_get_priority_max 0
#define sys_mlock 0
#define sys_munlock 0
#define sys_munlockall 0
#define sys_vhangup 0
#define sys_pivotroot 0
#define sys_chroot 0
#define sys_sync 0
#define sys_acct 0
#define sys_swapoff 0
#define sys_setdomainname 0
#define sys_iopl 0
#define sys_ioperm 0
#define sys_get_kernel_syms 0
#define sys_nfsservctl 0
#define sys_afs_syscall 0
#define sys_tuxcall 0
#define sys_security 0
#define sys_gettid 0
#define sys_lookup_dcookie 0
#define printargs 0
#define sys_set_tid_address 0
#define sys_timer_getoverrun 0
#define sys_timer_delete 0
#define sys_clock_getres 0
#define sys_vserver 0
#define sys_mq_unlink 0
#define sys_inotify_init 0
#define sys_mkdirat 0
#define sys_set_robust_list 0
#define sys_name_to_handle_at 0
#define sys_open_by_handle_at 0
#define sys_syncfs 0
#define sys_kcmp 0
#define sys_sched_setattr 0
#define sys_sched_getattr 0
#define sys_seccomp 0
#define sys_getrandom 0
#define sys_memfd_create 0
#define sys_kexec_file_load 0
#define sys_bpf 0
#define sys_execveat 0

// The following struct definition has been adapted from from https://github.com/bnoordhuis/strace/blob/master/defs.h#L390
typedef struct sysent {
  unsigned nargs;
  int sys_flags;
  int arg_type;
  const char *sys_name;
} struct_sysent;